### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Richard-Payne** [tomaustin700/AzureDevopsBuildCleanUpExtension#3]
I notice you say that Linux is not supported.  I had a look at the scripts and they don't seem too platform specific.   What was the problem that you found?

**Comment by tomaustin700** [comment]
Hi @Richard-Payne, it basically comes down to me not having any Linux agents to test it on. My environment is 100% Windows agents so I didn't give Linux anytime. I'm happy to accept a PR that adds Linux support though :)

**Comment by Richard-Payne** [comment]
Fair play.  I don't think a PR is needed.  Seems to be working fine.
