### ISSUE TITLE
alwise clean

### ISSUE THREAD

**Issue by avih75** [tomaustin700/AzureDevopsBuildCleanUpExtension#4]
i am looking for task that will run every time 
even if the build failed in a very early task, i nee it to clean the folder

**Comment by tomaustin700** [comment]
Hi @avih75, this can be accomplished by setting a condition on the task to always. See https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml%2Cstages
